server:
  port: 8082
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100

logging:
  level:
    com.example: debug
    org.springframework: warn

spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  servlet:
    multipart:
      max-file-size:  10MB
      max-request-size:  20MB
  devtools:
    restart:
      enabled: true


